name: MAVSDK-Swift-Example
options:
  deploymentTarget:
    iOS: "13.0"
  bundleIdPrefix: io.mavlink.mavsdk
settings:
  ENABLE_BITCODE: NO
packages:
  MAVSDK-Swift:
    url: https://github.com/mavlink/MAVSDK-Swift
    minorVersion: 0.9.0
targets:
  MAVSDK_Swift_Example:
    type: application
    platform: iOS
    info:
      path: MAVSDK-Swift-Example/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        UISupportedInterfaceOrientations:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
            UIInterfaceOrientationPortraitUpsideDown,
          ]
    settings:
    sources: [MAVSDK-Swift-Example]
    dependencies:
      - package: MAVSDK-Swift
        product: MAVSDK_Swift
      - package: MAVSDK-Swift
        product: MavsdkServer
